[toolchain]
channel = "nightly"
# channel = "1.92.0"
# See `rustup component list`
components = [
    "clippy",
    "rust-analyzer",
    "rust-docs",
    "rust-src",
    "rustfmt",
    "llvm-tools-preview",
]
